version: "3"
services:
  chrome:
    image: selenium/standalone-chrome:4.11
    shm_size: 2gb
    restart: always
    ports:
      - "4444:4444"
      - "7901:7900"
  app:
    build: ./app
    volumes:
      - ./app:/app
      - ./data:/data
    environment:
      SELENIUM_ENDPOINT: http://chrome:4444/wd/hub
    tty: true
    restart: always
